name: Build and deploy services

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  FE_DIRECTORY: ./code/frontend
  NUMBERS_DIRECTORY: ./code/numbers
  LUCKYSTARS_DIRECTORY: ./code/luckystars
  MERGE_DIRECTORY: ./code/merge
  TEST_DIRECTORY: ./code/tests
  
  FE_PACKAGE_PATH: ./code/frontend/publish
  NUMBERS_PACKAGE_PATH: ./code/numbers/publish
  LUCKYSTARS_PACKAGE_PATH: ./code/luckystars/publish
  MERGE_PACKAGE_PATH: ./code/merge/publish

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo 'Hello Test'
        #run: dotnet test "${{ env.TEST_DIRECTORY }}" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

  build-numbers-service:
    runs-on: ubuntu-latest
    needs: test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore
        run: dotnet restore "${{ env.NUMBERS_DIRECTORY }}"
      - name: Build
        run: dotnet build "${{ env.NUMBERS_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}
      - name: Publish
        run: dotnet publish "${{ env.NUMBERS_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --output "${{ env.NUMBERS_PACKAGE_PATH }}"
      - name: publish numbers service to Azure
        run: az
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.25.0
          inlineScript: |
            cd "${{ env.NUMBERS_PACKAGE_PATH }}"
            az webapp up -n cp1-web--numbers --os-type Linux --resource-group CPSFIA2.2. --runtime "DOTNET|5.0"
  build-letters-service:
      runs-on: ubuntu-latest
      needs: test
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        - name: Restore
          run: dotnet restore "${{ env.LUCKYSTARS_DIRECTORY }}"
        - name: Build
          run: dotnet build "${{ env.LUCKYSTARS_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}
        - name: Publish
          run: dotnet publish "${{ env.LUCKYSTARS_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --output "${{ env.LUCKYSTARS_PACKAGE_PATH }}"
    
        - name: publish numbers service to Azure
          run: az
        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      
        - name: Azure CLI script
          uses: azure/CLI@v1
          with:
            azcliversion: 2.25.0
            inlineScript: |
              cd "${{ env.LETTERS_PACKAGE_PATH }}"
              az webapp up -n cp1-web-luckystars --os-type Linux --resource-group CPSFIA2.2--runtime "DOTNET|5.0"
 
  build-merge-service:
    runs-on: ubuntu-latest
    needs: test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore
        run: dotnet restore "${{ env.MERGE_DIRECTORY }}"
      - name: Build
        run: dotnet build "${{ env.MERGE_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}
      - name: Publish
        run: dotnet publish "${{ env.MERGE_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --output "${{ env.MERGE_PACKAGE_PATH }}"
      - name: publish numbers service to Azure
        run: az
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.25.0
          inlineScript: |
            cd "${{ env.MERGE_PACKAGE_PATH }}"
            az webapp up -n cp1-web--merge --os-type Linux --resource-group CPSFIA2.2 --runtime "DOTNET|5.0"
            az webapp config appsettings set -g CPSFIA2.2 -n cp1-web--merge --settings "@../../../.github/workflows/mergeSettings.json"
  build-frontend-service:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore
        run: dotnet restore "${{ env.FE_DIRECTORY }}"
      - name: Build
        run: dotnet build "${{ env.FE_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}
      - name: Publish
        run: dotnet publish "${{ env.FE_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --output "${{ env.FE_PACKAGE_PATH }}"
      - name: publish numbers service to Azure
        run: az
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.25.0
          inlineScript: |
            cd "${{ env.FE_PACKAGE_PATH }}"
            az webapp up -n cp1-web-frontend --os-type Linux --resource-group CPSFIA2.2 --runtime "DOTNET|5.0"
            az webapp config appsettings set -g CPSFIA2.2 -n cp1-web-frontend --settings "@../../../.github/workflows/frontendSettings.json"